spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    # Note: You can actually remove the line below;
    # Spring Boot 3+ detects PostgreSQL automatically.
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081